# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ProjectName: WorthTheCandle
      ItchUsername: maddoscientisto
      ItchGameId: worth-the-candle-gb
      ItchBuildChannel: webgl

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - uses: actions/checkout@v3
      with:
        repository: chrismaltby/gb-studio
        ref: 'v3.1.0'
        path: "gb-studio"
    
    - name: Access cloned repository content
      run: |
            cd gb-studio
    
    - name: Build GB Studio CLI
      run: |
            cd gb-studio
            yarn
            npm run make:cli
            yarn link
            chmod 777 /usr/local/bin/gb-studio-cli
            cd ..
    
    - name: Build the game
      run: |        
            mkdir out
            gb-studio-cli make:rom ${{env.ProjectName}}.gbsproj out/${{env.ProjectName}}.gb
            gb-studio-cli make:web ${{env.ProjectName}}.gbsproj out/web/
            
    - name: Upload rom
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: Rom # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: out/${{env.ProjectName}}.gb
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
        
    - name: Upload web
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: Web # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: out/web/*
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error

    - name: Upload to itch
      uses: KikimoraGames/itch-publish@v0.0.3
      with:
        butlerApiKey: ${{secrets.BUTLER_API_KEY}}
        gameData: out/web/
        itchUsername: ${{env.ItchUsername}}
        itchGameId: ${{env.ItchGameId}}
        buildChannel: webgl

    - name: Upload to itch
      uses: KikimoraGames/itch-publish@v0.0.3
      with:
        butlerApiKey: ${{secrets.BUTLER_API_KEY}}
        gameData: out/${{env.ProjectName}}.gb
        itchUsername: ${{env.ItchUsername}}
        itchGameId: ${{env.ItchGameId}}
        buildChannel: gameboy
